export const AUTH_CHECK = "AUTH_CHECK"
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS"
export const AUTH_CHECK_FAIL = "AUTH_CHECK_FAIL"

export const RESIZE_CHART = "RESIZE_CHART"
export const RESIZE_CHART_SUCCESS = "RESIZE_CHART_SUCCESS"
export const RESIZE_CHART_FAIL = "RESIZE_CHART_FAIL"

export const CHANGE_COUNT = "CHANGE_COUNT"
export const CHANGE_COUNT_SUCCESS = "CHANGE_COUNT_SUCCESS"
export const CHANGE_COUNT_FAIL = "CHANGE_COUNT_FAIL"

export const GET_BLURS = "GET_BLURS"
export const GET_BLURS_SUCCESS = "GET_BLURS_SUCCESS"
export const GET_BLURS_FAIL = "GET_BLURS_FAIL"

export const GET_LOCATIONS = "GET_LOCATIONS"
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS"
export const GET_LOCATIONS_FAIL = "GET_LOCATIONS_FAIL"

export const GET_BRANDS = "GET_BRANDS"
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS"
export const GET_BRANDS_FAIL = "GET_BRANDS_FAIL"

export const GET_ZONES = "GET_ZONES"
export const GET_ZONES_SUCCESS = "GET_ZONES_SUCCESS"
export const GET_ZONES_FAIL = "GET_ZONES_FAIL"

export const GET_CASH_DESKS = "GET_CASH_DESKS"
export const GET_CASH_DESKS_SUCCESS = "GET_CASH_DESKS_SUCCESS"
export const GET_CASH_DESKS_FAIL = "GET_CASH_DESKS_FAIL"

export const ADD_WIDGET = "ADD_WIDGET"
export const ADD_WIDGET_SUCCESS = "ADD_WIDGET_SUCCESS"
export const ADD_WIDGET_FAIL = "ADD_WIDGET_FAIL"

export const ADD_CHART = "ADD_CHART"
export const ADD_COUNT = "ADD_COUNT"

export const REMOVE_CHART = "REMOVE_CHART"
export const REMOVE_CHART_SUCCESS = "REMOVE_CHART_SUCCESS"
export const REMOVE_CHART_FAIL = "REMOVE_CHART_FAIL"

export const REMOVE_COUNT = "REMOVE_COUNT"
export const REMOVE_COUNT_SUCCESS = "REMOVE_COUNT_SUCCESS"
export const REMOVE_COUNT_FAIL = "REMOVE_COUNT_FAIL"